@startuml クラス図

class ドリンク {
- サイズ

}

class フード {
- 種別

}

class 商品 {
- 名称
- 単価

}

class 注文明細 {
- 合計

}

class 注文 {
- 数量
- 小計

}

class カップ {
- サイズ

}

class 材料 {

}

class ハンバーガー {
- パン
- 肉
- 野菜
- チーズ

}

class 割引クーポン {
- 値引き額
- 期限

}

class レシピ {

}

class ポテト {
- 種別

}


@enduml