@startuml 客が自動販売機から商品を手に取るまでのシーケンス図
hide footbox
skinparam style strictuml /' 厳密なUMLに準拠する'/
Actor 客 as user
participant "料金装置" as pricequipment
participant "ボタン" as button
participant "ベンダー装置" as vendorequipment

user -> pricequipment : お金を投入する
user -> button : ボタンを押す
vendorequipment -> pricequipment : 売上を更新する
pricequipment -> user: 商品が出てくる
user -> pricequipment : 商品を受け取る


@enduml