@startuml ステートマシン図

[*] --> 電源SWOFF

state 電源SWOFF {
  [*] --> 停止状態
  停止状態 --> 電源SWON : 電源SWをONにする
}

state 電源SWON {
  [*] --> 停止状態

  state 停止状態 {
    光センサーが黒いライン上にあると判断する : 右モータOFF、左モータONにする
    光センサーがラインを外れると判断する : 右モータON、左モータOFFにする
    光センサーが黒いライン上にあると判断する --> 右旋回 : ライントレーサーは右旋回を始める
    光センサーがラインを外れると判断する --> 左旋回 : ライントレーサーは左旋回を始める
  }

  state 右旋回 {
    ラインの右境界線上を進む : ライントレーサーはラインの右境界線上を進む
    ラインの右境界線上を進む --> 右旋回 : ライントレーサーは右旋回を続ける
    ラインの右境界線上を進む --> 停止状態 : ラインの右境界線から外れる
  }

  state 左旋回 {
    ラインの右境界線上を進む : ライントレーサーはラインの右境界線上を進む
    ラインの右境界線上を進む --> 左旋回 : ライントレーサーは左旋回を続ける
    ラインの右境界線上を進む --> 停止状態 : ラインの右境界線から外れる
  }
}
@enduml
