@startuml
top to bottom direction
object "注文" as k1 {
- 注文日：2021/11/21
- 顧客：高橋洋平さん
}
object "注文明細" as k2 {
- 型式：V12345
- 数量：２
- 価格：50000
}
object "商品" as k3 {
- 型式：V12345
- 諸品名：テレビ
- 価格：50000
}
object "注文明細" as k4 {
- 型式：R8765
- 数量：1
- 価格：70000
}
object "商品" as k5 {
- 型式：R8765
- 諸品名：冷蔵庫
- 価格：70000
}
object "注文" as k6 {
- 注文日：2021/12/23
- 顧客：髙田利恵さん
}

object "注文明細" as k7 {
- 型式：R8765
- 数量：1
- 価格：70000

}

object "商品" as k8 {
- 型式：R8765
- 諸品名：冷蔵庫
- 価格：70000
}

object "注文" as k9 {
- 注文日：2021/12/30
- 顧客：大坪直之さん
}

k1 <-- k2
k2 <-- k4
k6 <-- k7
k3 <-- k5

@enduml